project:
title: "WP-RAPM for NCAA Basketball"
output-dir: _site
format:
html:
toc: true
number-sections: true
code-fold: true
df-print: paged
execute:
echo: true
warning: false
message: false
freeze: auto
editor: visual